
api: 
  name: gopu
  image:
    repository: etzba/gopu
    tag: "development"
  url: gopu-svc
  containerPort: 8080
  resources:
    limits:
      cpu: 400m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
