name: gopu
image:
  repository: ghcr.io/etzba/gopu
  tag: "latest"
pullSecret: ghcr-secret
containerPort: 8080
resources:
  limits:
    cpu: 400m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 512Mi
nodeSelector: {}
tolerations: []
affinity: {}

secretDistributions:
  dockerHub:
    name: docker-apitoken
    secretName: docker-auth
  ghcr:
    name: ghcr-apitoken
    secretName: ghcr-auth
  ghcrDockerConfig:
    name: ghcr-docker-config
    secretName: ghcr-secret