version: '3'

services:
  gopu:
    image: etzba/gopu:latest
    environment:
      - RELEASE_STAGE=testing
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
