{{- range .Values.secretDistributions }}
apiVersion: secdist.etzba.com/v1
kind: Distribution
metadata:
  labels:
    app.kubernetes.io/name: secret-distributor
  name: {{ .name }}-distribution
spec:
  secretName: {{ .secretName }}
{{- end }}